name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pylint
        run: |
          pylint main.py transform.py
      - name: Test with pytest
        run: |
          coverage run -m pytest test.py
      - name: Coverage report
        run: |
          coverage report -m